Cache the stride
TudbuT/micro_ndarray pull request #2
Opened 2023-05-07 08:30 UTC by Tnze

It's better to cache the stride to make `get` faster.

This is a simple proof, which should be thoroughly reviewed and tested before being merged.

2023-05-07 12:12 UTC, TudbuT commented
Looks good to me, will perform some tests and checks in a moment and merge if everything is good.

2023-05-10 15:52 UTC, TudbuT requested changes
this has a bug i think. i will have to locally pull this and do some tests to confirm this.

2023-05-10 15:52 UTC, TudbuT commented on src/array.rs
> +            stride[i] = l;
shouldn't stride be assigned to *before* multiplying?

2023-05-10 15:52 UTC, TudbuT commented on src/array.rs
> +            stride[i] = l;
same goes for here

2023-05-10 15:52 UTC, TudbuT commented on src/array.rs
> +            stride[i] = l;
and here.

2023-05-10 15:52 UTC, TudbuT commented on src/array.rs
> +            stride[i] = l;
and here.

reason for this is that stride[0] will be size[0], which messes lots of things up, i think.

2023-05-10 16:05 UTC, TudbuT commented
Suspicions confirmed: This writes out of bounds.

2023-05-10 16:11 UTC, TudbuT commented
![SmartSelect_20230510_180949_Flexcil](https://github.com/TudbuT/micro_ndarray/assets/48156391/a2b63853-a7a0-4852-9219-a3a2ce02e711)
This is confirmed by tests.

2023-05-10 16:18 UTC, TudbuT commented
Good news is that this is really easily fixed by reversing the order of the assignments.

2023-05-11 04:46 UTC, Tnze commented
Thank you, I fixed it. I also enabled `Allow edits by maintainers` so you can commit to my fork if necessary.

2023-05-11 05:35 UTC, TudbuT approved these changes

2023-05-11 05:37 UTC, TudbuT commented
Alright, I'll add the new cache system to the unchecked methods this afternoon and then merge. You can do that as well if you have time, but no pressure :P

2023-05-11 13:36 UTC, TudbuT commented
benchmarked, tested, works, yay!

it's not MUCH better performance, but good 'nuf.

2023-05-11 13:36 UTC, merged